import type {
  CorrectiveActionRow,
  EvidenceItemRow,
  FacilityRow,
  ObligationRow,
  WorkspaceDocumentRow,
  WorkspaceOverview,
} from "./types";

/** Representative pilot-preview data — never presented as a live client record. */
export const PILOT_PREVIEW: WorkspaceOverview = {
  mode: "pilot_preview",
  organizationName: "Sample Manufacturer (preview)",
  facilities: [
    {
      id: "preview-fac-1",
      organization_id: "preview-org",
      name: "Newark Plant",
      state: "New Jersey",
      industry: "Chemical Manufacturing",
      employee_count: "150-500",
      status: "pilot",
    },
  ],
  upcomingObligations: [
    {
      id: "preview-ob-1",
      organization_id: "preview-org",
      facility_id: "preview-fac-1",
      title: "Tier II / EPCRA reporting",
      source_document: "EPCRA program binder",
      source_citation: "40 CFR 370",
      jurisdiction: "Federal / NJ",
      frequency: "Annual",
      owner_name: "EHS Manager",
      evidence_required: "Submitted Tier II confirmation",
      status: "open",
      review_state: "draft",
      next_due_at: "2026-03-01",
      notes: "Pilot preview row — not live data.",
    },
    {
      id: "preview-ob-2",
      organization_id: "preview-org",
      facility_id: "preview-fac-1",
      title: "SPCC Plan 5-year review check",
      source_document: "SPCC Plan",
      source_citation: "40 CFR 112.5",
      jurisdiction: "Federal",
      frequency: "5-year",
      owner_name: "Facility Manager",
      evidence_required: "Review memo + PE certification status",
      status: "open",
      review_state: "reviewed",
      next_due_at: "2026-09-15",
      notes: "Pilot preview row — not live data.",
    },
  ],
  overdueActions: [
    {
      id: "preview-ca-1",
      organization_id: "preview-org",
      facility_id: "preview-fac-1",
      finding: "Secondary containment crack near drum storage",
      description: "Observed during monthly walkdown; temporary barrier in place.",
      owner_name: "Maintenance Lead",
      due_date: "2026-06-01",
      priority: "high",
      evidence_required: "Repair photo + work order closeout",
      evidence_link: null,
      status: "awaiting_evidence",
      reviewer_name: null,
      notes: "Pilot preview row — not live data.",
    },
  ],
  awaitingReview: [
    {
      id: "preview-ca-2",
      organization_id: "preview-org",
      facility_id: "preview-fac-1",
      finding: "Eyewash inspection overdue documentation",
      description: "Inspection completed; evidence packet needs EHS sign-off.",
      owner_name: "Safety Coordinator",
      due_date: "2026-07-20",
      priority: "medium",
      evidence_required: "Signed inspection checklist",
      evidence_link: null,
      status: "awaiting_review",
      reviewer_name: null,
      notes: "Pilot preview row — not live data.",
    },
  ],
  missingEvidence: [
    {
      id: "preview-ev-1",
      organization_id: "preview-org",
      facility_id: "preview-fac-1",
      title: "Hazard communication refresher attendance",
      required_proof: "Signed roster PDF",
      status: "missing",
      last_reviewed_at: null,
      notes: "Pilot preview row — not live data.",
    },
  ],
  recentDocuments: [
    {
      id: "preview-doc-1",
      organization_id: "preview-org",
      facility_id: "preview-fac-1",
      title: "Facility SPCC Plan (redacted sample)",
      doc_type: "plan",
      approval_status: "approved",
      notes: "Pilot preview — approved-source example only.",
    },
  ],
  latestBriefingLabel: "Sample Monthly Briefing (July 2026) — representative",
};

export function emptyLiveOverview(orgName: string | null, facilities: FacilityRow[]): WorkspaceOverview {
  return {
    mode: "live",
    organizationName: orgName,
    facilities,
    upcomingObligations: [] as ObligationRow[],
    overdueActions: [] as CorrectiveActionRow[],
    awaitingReview: [] as CorrectiveActionRow[],
    missingEvidence: [] as EvidenceItemRow[],
    recentDocuments: [] as WorkspaceDocumentRow[],
    latestBriefingLabel: null,
  };
}
